<?php
/**
 * @var $this Emzee_Dev_Block_Info
 */
?>
<?php
/**
 * @var $label string Label
 * @var $variable Emzee_Dev_Model_Debug_Object Variable to debug
 */
?>
<?php
$_id = $this->getHtmlId();
?>
<div id='<?php echo $_id; ?>' class='emzee-dev-debug-container'>
  <h1 class='handle'><?php echo $variable->getReflectionClass()->getName(); ?><span id='emzee-dev-debug-main-toggle' class='expandable'>Toggle</span></h1>
  <div id='emzee-dev-debug-container-content'>
    <?php if ($label): ?>
    <div style='font-weight:bold;'><?php echo $label; ?></div>
    <?php endif; ?>

    <?php echo $this->getChildHtml('classHierarchy'); ?>
    <?php echo $this->getChildHtml('blockClass'); ?>
    <?php echo $this->getChildHtml('backtrace'); ?>

  </div>

<?php echo $this->_getCssCode($_id); ?>
<?php echo $this->_getJsCode($_id); ?>

</div>
